### ISSUE TITLE
Update socket.io code to use separate namespaces and new v.7 code

### ISSUE THREAD

**Issue by mattmcmanus** [mattmcmanus/statusQuo#1]

**Comment by nicholaides** [comment]
What's the purpose of using separate channels?

**Comment by mattmcmanus** [comment]
I meant channels. I want to create a separate ping channel so as I build out websocket support the ping is isolated. I need to more intelligently manage resources. When i ping a server I spawn a child process and if the client code doesn't send the proper quit the spawned processes stay open and running. 

PS/. Did you get an email when I created this? Sorry dude. I didn't know that would happen.

**Comment by nicholaides** [comment]
Yeah, I got an email. Maybe I shouldn't be a collaborator on the project.
